apiVersion: v1
kind: Service
metadata:
  name: {{ include "verification-server.fullname" . }}
  labels:
    {{- include "verification-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if (eq .Values.service.type "ClusterIP") }}
      nodePort: null
      {{- end }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "verification-server.selectorLabels" . | nindent 4 }}
